services:
  postgres:
    image: postgres:15-alpine
    container_name: pizzaria_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pizzaria_user
      POSTGRES_PASSWORD: pizzaria_password
      POSTGRES_DB: pizzaria_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - pizzaria_network

volumes:
  postgres-data:
    driver: local

networks:
  pizzaria_network:
    driver: bridge
